version: '3'
services:
  generate-presentation:
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      bash -c "pandoc -t beamer presentation.md -o presentation.pdf
      && pandoc -t slidy -s presentation.md -o presentation.html"